version: '3'
services:
    website:
        build:
            context: .
            dockerfile: ./docker/prod/Dockerfile
        image: website
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www'
        depends_on:
            - db
        networks:
            - app-network
    db:
        image: 'mysql/mysql-server:8.0'
        restart: always
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'api_db'
            MYSQL_USER: 'api_user'
            MYSQL_PASSWORD: 123
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
        volumes:
            - 'api-mysql:/var/lib/mysql'
        networks:
            - app-network
volumes:
    api-mysql:
        driver: local

networks:
  app-network:
    driver: bridge